import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Camera, ShieldCheck, Users } from 'lucide-react';
import { Logo } from './Brand';
import { MobileMenu } from './MobileMenu';

export function LandingPage() {
  return <div className="r-public">
    <header className="site-header"><div className="container nav-wrap"><Logo/><nav className="desktop-nav" aria-label="Main navigation"><a href="#how">How it works</a><a href="#businesses">For businesses</a><a href="#workers">For workers</a></nav><div className="nav-actions"><Link className="text-link nav-login" to="/login">Log in</Link><Link className="button button--small button--ink" to="/signup">Get started <ArrowRight size={16}/></Link><MobileMenu/></div></div></header>
    <main><section className="hero"><div className="hero-glow hero-glow--one"/><div className="hero-glow hero-glow--two"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> PEOPLE MAKE THE DIFFERENCE</div><h1>Real people.<br/>Real <em>reach.</em></h1><p>Connect your business with people on Instagram.<br/>Or find tasks you can earn from.</p><div className="hero-actions"><Link className="button button--coral button--large" to="/signup?role=business">I'm a business <ArrowRight size={18}/></Link><Link className="button button--ghost button--large" to="/signup?role=worker">I want to earn <ArrowUpRight size={18}/></Link></div><div className="rr-hero-note"><Camera size={18}/><span>Instagram first. Made for Nigeria.</span></div></div><div className="hero-visual"><div className="photo-frame"><img src="/realreach-hero.webp" alt="An entrepreneur using her phone in a creative studio" fetchPriority="high"/><div className="photo-shade"/><div className="floating-card floating-card--bottom"><span className="mini-icon mini-icon--lime"><Users size={22}/></span><div><strong>People, not bots.</strong><small>That’s the point.</small></div></div></div><div className="orbit-label orbit-label--one"><Camera size={16}/> Start on Instagram</div></div></div><div className="container signal-strip"><span>REAL PEOPLE</span><i/><span>INSTAGRAM TASKS</span><i/><span>CLEAR RULES</span></div></section>
    <section className="section" id="how"><div className="container"><div className="section-heading"><span className="section-kicker">HOW IT WORKS</span><h2>Less guesswork.<br/>More connection.</h2></div><div className="value-grid rr-how-grid">{[['01','Businesses set the task','Choose the Instagram action and how many people you want to take part.'],['02','People do the work','Workers choose a task and complete it on their own Instagram account.'],['03','Work gets checked','Each action must pass its checks before a reward can be released.']].map(([n,t,p])=><article className="rr-how-card" key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="section rr-paths"><div className="container path-grid"><article className="path-card path-card--business" id="businesses"><Camera size={28}/><span className="section-kicker">FOR BUSINESSES</span><h3>Put your Instagram<br/>in good company.</h3><p>Set up your business, prepare a campaign and keep your results in one place.</p><Link className="button button--light" to="/signup?role=business">Create a business account <ArrowRight size={18}/></Link></article><article className="path-card rr-worker-card" id="workers"><Users size={28}/><span className="section-kicker">FOR WORKERS</span><h3>Your phone.<br/>Your next opportunity.</h3><p>See the task, the reward and the rules before you decide to take part.</p><Link className="button button--ink" to="/signup?role=worker">Create a worker account <ArrowRight size={18}/></Link></article></div></section>
    <section className="container rr-public-trust"><ShieldCheck size={24}/><div><h2>Your Instagram password stays yours.</h2><p>RealReach will never ask you to share it.</p></div><Link to="/help">Questions? <ArrowUpRight size={18}/></Link></section></main>
    <footer className="rr-footer"><div className="container"><Logo/><nav aria-label="Footer"><Link to="/help">Help</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/login">Log in</Link></nav><span>© {new Date().getFullYear()} RealReach</span></div></footer>
  </div>;
}
