import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, NavLink, Navigate, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, Clock3, Copy, FlaskConical, Home, Camera, LogOut, RefreshCw, ShieldCheck, UserRound, Wallet, X, Building2, LockKeyhole } from 'lucide-react';
import { Logo } from '../journey/ui';
import { useAuth } from './AuthContext';
import { command, db, friendlyError, pilotColumns, type Business, type Connection, type Pilot } from './client';
import { Notice } from './AuthPages';

export function Guard({children,admin=false}:{children:ReactNode;admin?:boolean}) {
  const auth=useAuth();
  if(auth.loading || (auth.user&&!auth.profile&&!auth.error))return <div className="r-loading" role="status"><Logo/><span>Opening your workspace…</span></div>;
  if(!auth.user)return <Navigate to="/login" replace/>;
  if(auth.error)return <div className="r-loading"><Notice error>{auth.error}</Notice><button className="r-button" onClick={()=>void auth.refresh()}>Retry</button></div>;
  if(admin&&!auth.isAdmin)return <div className="r-loading"><ShieldCheck size={40}/><h1>This space is restricted.</h1><p>Your account does not have administrator access.</p><Link className="r-button" to="/account">Back to your account</Link></div>;
  return children;
}
export function Workspace({children}:{children:ReactNode}){
  const auth=useAuth(),location=useLocation(),navigate=useNavigate(),[error,setError]=useState(''),[leaving,setLeaving]=useState(false);
  const front=location.pathname.startsWith('/business')?'business':location.pathname.startsWith('/admin')?'admin':'worker';
  const root=front==='business'?'/business':front==='admin'?'/admin':'/earn';
  const links=front==='admin'?[['/admin','Overview',ShieldCheck],['/account','Account',UserRound]] as const:[
    [root,'Overview',Home],[`${root}/instagram`,'Instagram',Camera],[`${root}/wallet`,'Wallet',Wallet],['/account','Account',UserRound],
  ] as const;
  async function logout(){setLeaving(true);try{await auth.signOut();navigate('/login',{replace:true});}catch(e){setError(friendlyError(e));}finally{setLeaving(false);}}
  return <div className="r-workspace"><aside className="r-sidebar"><Logo/><span className="r-sidebar-label">YOUR WORKSPACE</span><nav aria-label="Workspace navigation">{links.map(([to,title,Icon])=><NavLink end key={to} to={to}><Icon size={19}/>{title}<ChevronRight size={14}/></NavLink>)}</nav><div className="r-sidebar-note"><FlaskConical size={21}/><strong>Build trust first.</strong><p>You’re in the early-access pilot. Payments and paid campaigns are not live.</p><a href="/demo/earn">Explore the product demo <ArrowUpRight size={14}/></a></div><button className="r-signout" disabled={leaving} onClick={()=>void logout()}><LogOut size={18}/>{leaving?'Signing out…':'Sign out'}</button></aside>
    <div className="r-workspace-main"><header className="r-topbar"><div className="r-mobile-brand"><Logo/></div><div className="r-breadcrumb">Workspace <span>/</span> <strong>{front==='business'?'Business':front==='admin'?'Administration':'Earner'}</strong></div><div className="r-top-actions"><label className="r-switcher"><span className="r-sr">Switch workspace</span><select value={front} onChange={e=>navigate(e.target.value==='business'?'/business':e.target.value==='admin'?'/admin':'/earn')}><option value="worker">Earner</option><option value="business">Business</option>{auth.isAdmin&&<option value="admin">Admin</option>}</select></label><Link className="r-avatar" to="/account" aria-label="Your account">{auth.profile?.display_name.slice(0,1).toUpperCase()||<UserRound size={19}/>}</Link></div></header>
    <main className="r-content">{error&&<Notice error>{error}</Notice>}{children}</main></div><nav className="r-bottomnav" aria-label="Mobile workspace navigation">{links.map(([to,title,Icon])=><NavLink end key={to} to={to}><Icon size={21}/><span>{title}</span></NavLink>)}</nav></div>;
}
export function PageHeading({kicker,title,text,children}:{kicker:string;title:string;text:string;children?:ReactNode}){return <header className="r-page-heading"><div><span className="r-kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></div>{children}</header>;}
export function Panel({title,text,children,className=''}:{title?:string;text?:string;children:ReactNode;className?:string}){return <section className={`r-panel ${className}`}>{title&&<header><h2>{title}</h2>{text&&<p>{text}</p>}</header>}{children}</section>;}
function useBusiness(){
  const {user}=useAuth();const [business,setBusiness]=useState<Business|null>(null),[connection,setConnection]=useState<Connection|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
  useEffect(()=>{let alive=true;setLoading(true);setError('');void (async()=>{
    const {data,error}=await db().from('businesses').select('id,name,owner_id').eq('owner_id',user!.id).maybeSingle();if(error)throw error;
    if(!alive)return;setBusiness(data);
    if(data){const result=await db().from('instagram_connections').select('id,business_id,owner_id,username,status,updated_at').eq('business_id',data.id).maybeSingle();if(result.error)throw result.error;if(alive)setConnection(result.data);}
  })().catch(e=>{if(alive)setError(friendlyError(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[user?.id,version]);
  return {business,connection,error,loading,reload:()=>setVersion(v=>v+1)};
}
function BusinessForm({onSave}:{onSave:()=>void}){
  const {user}=useAuth(),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await db().from('businesses').insert({owner_id:user!.id,name:name.trim()});if(error)throw error;onSave();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Panel title="Give your business a home." text="Start with your name. You’ll connect your professional Instagram account next."><form className="r-form" onSubmit={submit}>{error&&<Notice error>{error}</Notice>}<label>Business name<input required minLength={2} maxLength={100} placeholder="Your business or brand name" value={name} onChange={e=>setName(e.target.value)}/></label><button className="r-button" disabled={busy}>{busy?'Saving…':'Create business profile'}<ArrowRight size={18}/></button></form></Panel>;
}
export function Overview({business=false}:{business?:boolean}){
  const {profile}=useAuth();const root=business?'/business':'/earn';
  return <Workspace><PageHeading kicker={business?'YOUR BUSINESS, IN GOOD COMPANY':'SMALL ACTIONS. REAL CONNECTIONS.'} title={`${profile?.display_name?`Hello, ${profile.display_name.split(' ')[0]}.`:'Welcome to RealReach.'}`} text={business?'Let’s get your business ready to meet real people.':'Let’s get your account ready for your first opportunity.'}/>
    {!profile?.display_name&&<Notice>Finish your account details to make this space yours. <Link to="/account">Complete profile <ArrowRight size={14}/></Link></Notice>}
    <section className="r-feature"><div><span className="r-pill"><span/> INSTAGRAM-FIRST PILOT</span><h2>{business?<>Your next chapter<br/>starts with a connection.</>:<>Real participation.<br/>Trust you can build.</>}</h2><p>{business?'Connect your account, invite your testers and see verification happen one clear step at a time.':'Join an invited Instagram test and follow the proof journey—from account check to final observation.'}</p><Link className="r-button r-button-lime" to={`${root}/instagram`}>{business?'Set up Instagram':'Open your Instagram pilot'}<ArrowRight size={18}/></Link></div><div className="r-feature-art" aria-hidden="true"><div className="r-orbit"/><div className="r-orbit r-orbit-two"/><div className="r-instagram-tile"><Camera size={56}/></div><span className="r-art-proof"><ShieldCheck size={19}/> Evidence before earnings</span><span className="r-art-dot"/></div></section>
    <div className="r-section-title"><h2>Your path to ready</h2><span>ONE STEP AT A TIME</span></div><div className="r-readiness">{[
      {num:'01',title:'Make it yours',text:'Add your name and choose your starting workspace.',to:'/account',done:!!profile?.display_name},
      {num:'02',title:business?'Connect your business':'Prove your participation',text:business?'Authorize Instagram securely. No password sharing.':'Use a private invitation to join a real verification test.',to:`${root}/instagram`,done:false},
      {num:'03',title:'A clear money trail',text:'Funding and payouts arrive after the verified pilot.',to:`${root}/wallet`,done:false},
    ].map(item=><Link className="r-readiness-card" key={item.num} to={item.to}><span className={item.done?'r-step done':'r-step'}>{item.done?<Check size={18}/>:item.num}</span><h3>{item.title}</h3><p>{item.text}</p><span className="r-card-link">{item.done?'Review details':'Take a look'}<ArrowRight size={17}/></span></Link>)}</div>
    <div className="r-note-row"><ShieldCheck size={22}/><p><strong>A real account. A controlled pilot.</strong><br/>Your profile is saved securely. Pilot checks carry no cash reward, and payments are not enabled.</p><a href="/demo/earn">See the demo <ArrowUpRight size={16}/></a></div>
  </Workspace>;
}
export function BusinessInstagram(){
  const state=useBusiness(),[params]=useSearchParams(),navigate=useNavigate();
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[invite,setInvite]=useState(''),[confirmDisconnect,setConfirmDisconnect]=useState(false);
  const callback=params.get('attempt'),returnedError=params.get('error');
  async function action(name:string){setBusy(true);setError('');setNotice('');try{
    if(name==='connect-start'){const data=await command<{url:string}>(name);window.location.assign(data.url);return;}
    if(name==='connect-complete'){await command(name,{attempt:callback,state:params.get('rr_state'),accountId:params.get('accountId')});navigate('/business/instagram',{replace:true});setNotice('Instagram account confirmed. You can now invite your testers.');state.reload();}
    if(name==='invite-create'){const data=await command<{invite:string}>(name);setInvite(data.invite);}
    if(name==='disconnect'){await command(name);setConfirmDisconnect(false);state.reload();setNotice('Instagram disconnected. Pending checks will wait for a reconnection.');}
  }catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Workspace><PageHeading kicker="BUSINESS / CONNECTIONS" title="Your Instagram, connected." text="One secure connection. A clear record of what happens next."/><div className="r-two-column"><div>
    {(error||state.error)&&<Notice error>{error||state.error}</Notice>}{notice&&<Notice>{notice}</Notice>}
    {returnedError&&<Notice error>Instagram authorization was cancelled or unsuccessful. Your account was not marked connected. Start again when you’re ready.</Notice>}
    {state.loading?<Panel><p role="status">Loading your business…</p></Panel>:!state.business?<BusinessForm onSave={state.reload}/>:<>
      <Panel className="r-connection-panel"><div className="r-connection-head"><span className="r-service-icon"><Camera size={27}/></span><div><span className="r-kicker">INSTAGRAM</span><h2>{state.connection?.username?`@${state.connection.username}`:state.business.name}</h2><span className={`r-status ${state.connection?.status==='connected'?'good':''}`}>{state.connection?.status==='connected'?'Connected':'Not connected'}</span></div></div><p>Connect a Business or Creator account you own. You’ll authorize directly with Instagram through our provider. RealReach never receives your Instagram password.</p>
      {callback&&!returnedError?<button className="r-button" disabled={busy} onClick={()=>void action('connect-complete')}>{busy?'Confirming…':'Finish secure connection'}<ShieldCheck size={18}/></button>:<button className="r-button" disabled={busy} onClick={()=>void action('connect-start')}>{busy?'Opening secure connection…':state.connection?.status==='connected'?'Refresh authorization':'Connect Instagram'}<ArrowUpRight size={18}/></button>}
      <p className="r-small">Provider setup and pilot approval are required. A button click alone never confirms a connection.</p></Panel>
      <Panel title="Invite your first testers" text="This private, unpaid pilot proves the account and follow-check flow before campaigns go live."><div className="r-invite-meta"><span><UserRound size={18}/> Up to 10 claims per code</span><span><Clock3 size={18}/> Expires in 7 days</span></div><button className="r-button r-button-outline" disabled={busy||state.connection?.status!=='connected'} onClick={()=>void action('invite-create')}>Create pilot invitation<ArrowRight size={17}/></button>{invite&&<div className="r-copy-box"><label>Private invitation code<textarea readOnly value={invite}/></label><CopyButton text={invite}/><small>Save this code now. It is not recoverable after leaving this page.</small></div>}</Panel>
      {state.connection?.status==='connected'&&<Panel title="Connection controls"><p>Disconnecting pauses verification. It does not delete pilot history.</p>{confirmDisconnect?<Notice><p>Revoke this Instagram connection?</p><div className="r-button-row"><button className="r-button r-button-danger" disabled={busy} onClick={()=>void action('disconnect')}>Yes, disconnect</button><button className="r-text-button" onClick={()=>setConfirmDisconnect(false)}>Keep connection</button></div></Notice>:<button className="r-text-button" onClick={()=>setConfirmDisconnect(true)}>Disconnect Instagram</button>}</Panel>}
      <PilotList business/>
    </>}
    </div><aside><Panel className="r-guide-panel" title="What happens next"><ol className="r-guide"><li><span>1</span><div><strong>You authorize Instagram</strong><p>We confirm the account with the provider, not browser-supplied details.</p></div></li><li><span>2</span><div><strong>Your tester sends a code</strong><p>A signed message event links their Instagram identity to their pilot.</p></div></li><li><span>3</span><div><strong>We observe the action</strong><p>Initial and delayed checks show positive, negative or unknown evidence.</p></div></li></ol><div className="r-small-note"><LockKeyhole size={18}/><p>No money moves in this pilot. Comments stay unavailable until their separate proof test passes.</p></div></Panel></aside></div></Workspace>;
}
export function CopyButton({text}:{text:string}){const [message,setMessage]=useState('');return <><button className="r-copy-button" onClick={()=>void navigator.clipboard.writeText(text).then(()=>setMessage('Copied.')).catch(()=>setMessage('Select the code above and copy it manually.'))}><Copy size={16}/> Copy code</button><span className="r-small" role="status">{message}</span></>;}
export function WorkerInstagram(){
  const [invite,setInvite]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
  async function join(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await command('join-pilot',{invite:invite.trim()});setInvite('');setVersion(v=>v+1);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Workspace><PageHeading kicker="EARNER / INSTAGRAM" title="Make the connection real." text="A private pilot to test account-level evidence. No screenshots. No cash rewards yet."/><div className="r-two-column"><div><Panel title="Have a pilot invitation?" text="Paste the private code shared by the test business. Use your own Instagram account."><form className="r-form" onSubmit={join}>{error&&<Notice error>{error}</Notice>}<label>Invitation code<input value={invite} onChange={e=>setInvite(e.target.value)} required pattern="[a-f0-9]{64}" maxLength={64} autoComplete="off" placeholder="Paste your pilot code"/></label><button className="r-button" disabled={busy}>{busy?'Joining…':'Join the pilot'}<ArrowRight size={18}/></button></form></Panel><PilotList key={version}/></div><aside><Panel className="r-guide-panel" title="Before you begin"><ol className="r-guide"><li><span>1</span><div><strong>Send your private DM code</strong><p>This identifies the Instagram account doing the work.</p></div></li><li><span>2</span><div><strong>Wait for the baseline check</strong><p>Don’t follow before we confirm you are eligible.</p></div></li><li><span>3</span><div><strong>Follow, then request a check</strong><p>A final observation follows the 48-hour pilot hold. An unavailable API is never guessed.</p></div></li></ol><div className="r-small-note"><ShieldCheck size={19}/><p>One Instagram identity per business and worker binding. Never share your private verification code.</p></div></Panel></aside></div></Workspace>;
}
const states:Record<string,[string,string]>={awaiting_identity:['Waiting for your message','Send the exact code below before it expires.'],checking_baseline:['Checking your starting point','Wait here before following. We’re checking whether you already follow this business.'],ready:['Ready for your action','Follow the business on Instagram, then request your check.'],checking_action:['Checking the follow','Your request is queued. You can leave this page and come back.'],holding:['Follow observed','The initial check passed. The final observation is scheduled after the hold.'],verified:['Pilot verified','Both follow checks passed. This was an unpaid test, not a payable assignment.'],not_eligible:['Already following','This pilot measures a new follow. Your baseline shows you already followed this business.'],not_retained:['Not following at final check','The final observation did not confirm the follow. No earnings were created.'],needs_review:['A check needs attention','We could not reach a reliable decision. No successful result has been assumed.'],expired:['Code expired','The identity message was not confirmed within the pilot window. Contact the team before another test.']};
function PilotList({business=false}:{business?:boolean}){
  const {user}=useAuth(),[pilots,setPilots]=useState<Pilot[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
  useEffect(()=>{let alive=true;async function load(){try{const result=await db().from('instagram_pilots').select(pilotColumns).eq(business?'owner_id':'worker_id',user!.id).order('created_at',{ascending:false}).limit(30);if(result.error)throw result.error;if(alive){setPilots(result.data as Pilot[]);setError('');}}catch(e){if(alive)setError(friendlyError(e));}finally{if(alive)setLoading(false);}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},15_000);return()=>{alive=false;clearInterval(timer);};},[user?.id,business,version]);
  return <section><div className="r-section-title"><h2>{business?'Your pilot activity':'Your verification journey'}</h2><button className="r-icon-button" aria-label="Refresh pilot activity" onClick={()=>setVersion(v=>v+1)}><RefreshCw size={18}/></button></div>{error&&<Notice error>{error}</Notice>}{loading?<Panel><p role="status">Loading pilot activity…</p></Panel>:pilots.length?pilots.map(p=><PilotCard key={p.id} pilot={p} business={business} reload={()=>setVersion(v=>v+1)}/>):<div className="r-empty"><span><FlaskConical size={28}/></span><h3>No pilot activity yet.</h3><p>{business?'Connect Instagram and share a private invitation to begin.':'Your first test will appear here after you enter an invitation.'}</p><small>Nothing to earn or withdraw until paid campaigns launch.</small></div>}</section>;
}
function PilotCard({pilot:p,business,reload}:{pilot:Pilot;business:boolean;reload:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[evidence,setEvidence]=useState<Array<{id:string;phase:string;result:string;observed_at:string}>>([]),[showEvidence,setShowEvidence]=useState(false);
  const expired=p.status==='awaiting_identity'&&Date.parse(p.expires_at)<Date.now();const [title,text]=states[expired?'expired':p.status]??['Pending','Waiting for the next observation.'];
  async function check(){setBusy(true);setError('');try{await command('check-pilot',{id:p.id});reload();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  async function receipt(){setBusy(true);setError('');try{const {data,error}=await db().from('instagram_evidence').select('id,phase,result,observed_at').eq('pilot_id',p.id).order('observed_at');if(error)throw error;setEvidence(data);setShowEvidence(true);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Panel className="r-pilot-card"><div className="r-pilot-top"><span className="r-service-icon"><Camera/></span><div><h3>{p.business_name}</h3><span>@{p.instagram_username}</span></div><span className="r-pill">UNPAID TEST</span></div><div className="r-pilot-progress" aria-label={`Pilot state: ${title}`}>{['Identity','Baseline','Action','Final check'].map((label,i)=><span key={label} className={i<({awaiting_identity:0,checking_baseline:1,ready:2,checking_action:2,holding:3,verified:4}[p.status]??0)?'complete':''}><i/>{label}</span>)}</div><h3>{title}</h3><p>{text}</p>{error&&<Notice error>{error}</Notice>}
    {!business&&p.status==='awaiting_identity'&&!expired&&<div className="r-challenge"><small>SEND THIS EXACT MESSAGE TO @{p.instagram_username}</small><code>{p.challenge}</code><CopyButton text={p.challenge}/><a className="r-button r-button-outline" href={`https://ig.me/m/${encodeURIComponent(p.instagram_username)}`} target="_blank" rel="noreferrer">Open Instagram messages<ArrowUpRight size={17}/></a><small>Expires {new Date(p.expires_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}. Return here after sending.</small></div>}
    {!business&&p.status==='ready'&&<div className="r-button-row"><a className="r-button r-button-outline" href={`https://www.instagram.com/${encodeURIComponent(p.instagram_username)}/`} target="_blank" rel="noreferrer">Open profile<ArrowUpRight size={16}/></a><button className="r-button" disabled={busy} onClick={()=>void check()}>{busy?'Requesting…':'I followed · check now'}<CheckCircle2 size={17}/></button></div>}
    {p.hold_until&&<p className="r-small"><Clock3 size={15}/> Final observation due after {new Date(p.hold_until).toLocaleString()}.</p>}
    <button className="r-text-button" disabled={busy} onClick={()=>void receipt()}>View verification history<ChevronRight size={16}/></button>{showEvidence&&<div className="r-evidence"><button className="r-icon-button" aria-label="Close verification history" onClick={()=>setShowEvidence(false)}><X size={17}/></button>{evidence.length?evidence.map(e=><div key={e.id}><strong>{e.phase} · {e.result}</strong><span>{new Date(e.observed_at).toLocaleString()}</span></div>):<p>No observations have been recorded yet.</p>}</div>}
  </Panel>;
}
export function WalletPage(){return <Workspace><PageHeading kicker="YOUR WALLET" title="Clear money. From day one." text="Your financial history will live here once funding and payouts are ready."/><section className="r-wallet-placeholder"><span className="r-icon-large"><Wallet size={32}/></span><span className="r-kicker">NOT ACTIVATED</span><h2>No live wallet yet.</h2><p>Instagram pilot checks do not create cash earnings. We won’t show a balance or accept a deposit until the payment integration is verified.</p><div className="r-wallet-features"><span><Check size={16}/> Pending and available earnings</span><span><Check size={16}/> Traceable transaction receipts</span><span><Check size={16}/> Verified bank withdrawals</span></div><a className="r-button r-button-outline" href="/demo/earn/wallet">Explore the sample wallet<ArrowUpRight size={17}/></a></section></Workspace>;}
export function AccountPage(){
  const auth=useAuth(),navigate=useNavigate(),[name,setName]=useState(auth.profile?.display_name??''),[city,setCity]=useState(auth.profile?.city??''),[front,setFront]=useState(auth.profile?.preferred_front??'worker'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{if(!auth.profile?.display_name&&sessionStorage.getItem('rr-onboarding-front')==='business')setFront('business');},[auth.profile?.display_name]);
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const {data,error}=await db().from('profiles').update({display_name:name.trim(),city:city.trim(),preferred_front:front}).eq('id',auth.user!.id).select('id').single();if(error||!data)throw error??new Error('Your profile could not be saved.');sessionStorage.removeItem('rr-onboarding-front');await auth.refresh();setMessage('Your profile is saved.');}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{await auth.signOut();navigate('/login',{replace:true});}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Workspace><PageHeading kicker="YOUR ACCOUNT" title="A little more you." text="Your details, your security, your place in RealReach."/><div className="r-two-column"><div><Panel title="Profile details" text="Choose how you appear and where you want to start.">{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}<form className="r-form" onSubmit={save}><label>Your name<input required minLength={2} maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input type="email" readOnly value={auth.user?.email??''}/><small>Your confirmed sign-in email.</small></label><label>City<input maxLength={80} autoComplete="address-level2" placeholder="e.g. Lagos" value={city} onChange={e=>setCity(e.target.value)}/></label><label>Starting workspace<select value={front} onChange={e=>setFront(e.target.value as 'worker'|'business')}><option value="worker">Earner</option><option value="business">Business</option></select><small>You can switch workspaces anytime. This does not grant admin permissions.</small></label><button className="r-button" disabled={busy}>{busy?'Saving…':'Save profile'}<Check size={18}/></button></form></Panel><SecurityPanel/><Panel title="End this session"><p>Sign out on this device. Your saved profile and pilot history remain in your account.</p><button className="r-button r-button-outline" disabled={busy} onClick={()=>void logout()}><LogOut size={18}/> Sign out</button></Panel></div><aside><Panel className="r-guide-panel" title="Your account, protected"><div className="r-security-list"><span><CheckCircle2/><div><strong>Confirmed email</strong><small>{auth.user?.email}</small></div></span><span><ShieldCheck/><div><strong>Private by default</strong><small>Your profile is not a public directory.</small></div></span><span><Building2/><div><strong>One login, two possibilities</strong><small>Use the same account to participate or grow your business.</small></div></span></div><Link className="r-button r-button-outline" to={front==='business'?'/business':'/earn'}>Open your workspace<ArrowRight size={17}/></Link></Panel></aside></div></Workspace>;
}
export function SecurityPanel({onVerified}:{onVerified?:()=>void}){
  const [factor,setFactor]=useState<string|null>(null),[qr,setQr]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verified,setVerified]=useState(false),[loaded,setLoaded]=useState(false);
  useEffect(()=>{let alive=true;void db().auth.mfa.listFactors().then(({data,error})=>{if(!alive)return;if(error)setError(friendlyError(error));else setFactor(data.totp.find(f=>f.status==='verified')?.id??null);setLoaded(true);});return()=>{alive=false;};},[]);
  async function enroll(){setBusy(true);setError('');try{const {data,error}=await db().auth.mfa.enroll({factorType:'totp',friendlyName:`RealReach ${new Date().toISOString().slice(0,19)}`});if(error)throw error;setFactor(data.id);setQr(data.totp.qr_code);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  async function verify(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await db().auth.mfa.challengeAndVerify({factorId:factor!,code});if(error)throw error;setVerified(true);setQr('');setCode('');onVerified?.();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  return <Panel title="An extra layer of security" text="Use an authenticator app for a second sign-in check. Required for administration.">{error&&<Notice error>{error}</Notice>}{verified?<Notice>Authenticator verified for this session.</Notice>:!loaded?<p role="status">Checking account security…</p>:factor?<form className="r-form" onSubmit={verify}>{qr&&<div className="r-qr"><img alt="Scan this QR code with your authenticator app" src={qr.startsWith('data:')?qr:`data:image/svg+xml;utf8,${encodeURIComponent(qr)}`}/><p>Scan with your authenticator app, then enter its six-digit code.</p></div>}<label>Authenticator code<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="r-button r-button-outline" disabled={busy}>{busy?'Verifying…':'Verify authenticator'}<ShieldCheck size={18}/></button></form>:<button className="r-button r-button-outline" disabled={busy} onClick={()=>void enroll()}>{busy?'Preparing…':'Set up authenticator'}<ShieldCheck size={18}/></button>}<Link className="r-text-button" to="/forgot-password">Reset your password<ArrowRight size={16}/></Link></Panel>;
}
export function AdminPage(){
  const [state,setState]=useState<{jobs:Array<{id:string;phase:string;state:string;attempts:number}>;instagramConfigured:boolean}|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
  useEffect(()=>{let alive=true;command<typeof state>('admin-status').then(data=>{if(alive){setState(data);setError('');}}).catch(e=>{if(alive)setError(friendlyError(e));});return()=>{alive=false;};},[revision]);
  return <Workspace><PageHeading kicker="SOLE ADMIN / PILOT OPERATIONS" title="Keep the ordinary path clear." text="Connection health and verification jobs. No payment controls are live."/>{error&&<Notice error>{error}</Notice>}<div className="r-two-column"><div>{state?<><Panel title="Integration readiness"><p>Instagram provider: <strong>{state.instagramConfigured?'Credential configured · live pilot still required':'Awaiting setup'}</strong></p><p>Payments: <strong>Disabled</strong></p></Panel><Panel title="Recent verification jobs">{state.jobs.length?state.jobs.map(job=><div className="r-job" key={job.id}><strong>{job.phase}</strong><span>{job.state}</span><small>{job.attempts} attempt(s)</small></div>):<div className="r-empty"><FlaskConical/><h3>No jobs yet.</h3><p>Signed identity messages will start the verification queue.</p></div>}</Panel></>:<Panel title="Verify your session"><p>Administration requires the designated account and a verified authenticator session. A workspace switch alone grants no access.</p></Panel>}</div><aside><SecurityPanel onVerified={()=>setRevision(v=>v+1)}/><button className="r-button r-button-outline" onClick={()=>setRevision(v=>v+1)}>Refresh status<RefreshCw size={17}/></button></aside></div></Workspace>;
}
